# Generated by Django 2.1.1 on 2018-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(default='blog/images/avatar.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
