# Generated by Django 2.1.1 on 2018-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(upload_to='blog/images/uploads/'),
        ),
    ]
