# Generated by Django 2.1.1 on 2018-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181124_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
