# Generated by Django 2.1.1 on 2018-11-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181125_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainPic',
            field=models.ImageField(upload_to='img/post/'),
        ),
    ]
