# Generated by Django 2.1.5 on 2019-03-17 02:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190306_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainPic',
            new_name='main_pic',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=15000),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
